---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30040
  selector:
    app: nexus
